version: '3.7'
services:
  mysql:
    container_name: mysql-esgi-rent
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: esgi-rent
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - esgi-rent:/var/lib/mysql
volumes:
  esgi-rent: