spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/esgi-rent
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true
  docker:
    compose:
      file: rent-properties-api/docker-compose.yaml
